/* Autogenerated by onion assets */
#ifndef __ASSETS_H_____SRC_INCLUDE_ASSETS_H
#define __ASSETS_H_____SRC_INCLUDE_ASSETS_H
# ifdef __cplusplus
extern "C"{
# endif
#include <onion/types.h>
void admin_html(onion_dict *context, onion_response *res);
void dashboard_html(onion_dict *context, onion_response *res);
void header_html(onion_dict *context, onion_response *res);
void index_html(onion_dict *context, onion_response *res);
void login_html(onion_dict *context, onion_response *res);
void orders_html(onion_dict *context, onion_response *res);
void profile_html(onion_dict *context, onion_response *res);
void register_html(onion_dict *context, onion_response *res);
// New data will be inserted over this line. DO NOT MODIFY (SPECIALLY THIS LINE).
# ifdef __cplusplus 
} // extern "C"
# endif 
#endif
